# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NationalPark' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NationalPark
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
	pod 'FirebaseFirestoreSwift'
  target 'NationalParkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NationalParkUITests' do
    # Pods for testing
  end

end
